# Generated by Django 5.2.15 on 2026-07-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('requested_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Negotiating', 'Negotiating'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offered_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_proposals', to='skills.skill')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='received_proposals', to=settings.AUTH_USER_MODEL)),
                ('requested_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_in_proposals', to='skills.skill')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sent_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('requested_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='proposals.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='idx_proposals_status'),
        ),
    ]
