# Generated by Django 5.2.16 on 2026-07-29 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='next_session_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['sender', 'archived'], name='idx_prop_sndr_arch'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['receiver', 'archived'], name='idx_prop_rcvr_arch'),
        ),
    ]
