# Generated by Django 5.2.16 on 2026-07-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_proposal_archived_proposal_message_proposal_muted_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='offered_skill',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='requested_skill',
        ),
        migrations.AddField(
            model_name='proposal',
            name='offered_skills',
            field=models.ManyToManyField(related_name='offered_in_proposals', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='requested_skills',
            field=models.ManyToManyField(related_name='requested_in_proposals', to='skills.skill'),
        ),
    ]
