# Generated by Django 5.2.16 on 2026-07-29 12:29

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('proposals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_messages_proposal',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_text',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('term_proposal', 'Term Proposal'), ('session_proposal', 'Session Proposal'), ('terms_updated', 'Terms Updated'), ('session_confirmed', 'Session Confirmed'), ('system', 'System')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='response_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),

        # ─── UUID transition via raw SQL ─────────────────────────────
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pgcrypto;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE messages ADD COLUMN uuid_id uuid;",
            reverse_sql="ALTER TABLE messages DROP COLUMN IF EXISTS uuid_id;",
        ),
        migrations.RunSQL(
            sql="UPDATE messages SET uuid_id = gen_random_uuid();",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE messages DROP CONSTRAINT messages_pkey CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE messages DROP COLUMN id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE messages RENAME COLUMN uuid_id TO id;
                ALTER TABLE messages ALTER COLUMN id SET NOT NULL;
                ALTER TABLE messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Tell Django the field state is now UUID
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # ─── Indexes ─────────────────────────────────────────────────
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['proposal', 'created_at'], name='idx_messages_proposal_created'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['proposal', 'message_type'], name='idx_messages_proposal_type'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['response_status'], name='idx_messages_response'),
        ),
    ]