# Generated by Django 5.2.17 on 2026-08-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('term_proposal', 'Term Proposal'), ('session_proposal', 'Session Proposal'), ('terms_updated', 'Terms Updated'), ('session_confirmed', 'Session Confirmed'), ('system', 'System')], default='text', max_length=20),
        ),
    ]
