# Generated by Django 5.2.15 on 2026-07-01 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('teach', 'Teach'), ('learn', 'Learn')], max_length=10)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Languages', 'Languages'), ('Music', 'Music'), ('Health & Fitness', 'Health & Fitness'), ('Arts', 'Arts'), ('Business', 'Business'), ('Other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'type', 'category'], name='idx_skills_lookup')],
            },
        ),
    ]
