# Generated by Django 5.2.15 on 2026-07-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('meeting_link', models.URLField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Attended', 'Attended'), ('Missed', 'Missed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=50)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='proposals.proposal')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
